run:
  timeout: 5m
  skip-dirs:
    - vendor
    - bin
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - "zz_generated.deepcopy.go"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - gofmt
    - goimports
    - misspell
  disable:
    - typecheck    # Disabled due to Go version mismatch between CI (1.23) and local (1.21)
    - staticcheck  # Disabled to reduce noise from dependency issues

linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - ineffassign
    # Exclude test directories
    - path: test/
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0