run:
  timeout: 5m
  skip-dirs:
    - vendor
    - bin
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - "zz_generated.deepcopy.go"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - misspell
  disable:
    - typecheck  # Disable typecheck as it's causing issues with embedded structs

linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - ineffassign
    # Exclude test directories
    - path: test/
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0