{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubejanitor-operator.fullname" . }}-manager
  labels:
    {{- include "kubejanitor-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - persistentvolumeclaims
  - persistentvolumes
  - configmaps
  - secrets
  - services
  - endpoints
  - events
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ops.k8s.io
  resources:
  - janitorpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.k8s.io
  resources:
  - janitorpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - ops.k8s.io
  resources:
  - janitorpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubejanitor-operator.fullname" . }}-manager
  labels:
    {{- include "kubejanitor-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubejanitor-operator.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "kubejanitor-operator.serviceAccountName" . }}
  namespace: {{ include "kubejanitor-operator.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubejanitor-operator.fullname" . }}-leader-election
  namespace: {{ include "kubejanitor-operator.leaderElectionNamespace" . }}
  labels:
    {{- include "kubejanitor-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubejanitor-operator.fullname" . }}-leader-election
  namespace: {{ include "kubejanitor-operator.leaderElectionNamespace" . }}
  labels:
    {{- include "kubejanitor-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubejanitor-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "kubejanitor-operator.serviceAccountName" . }}
  namespace: {{ include "kubejanitor-operator.namespace" . }}
{{- end }}