{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubejanitor-operator.serviceAccountName" . }}
  namespace: {{ include "kubejanitor-operator.namespace" . }}
  labels:
    {{- include "kubejanitor-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}